# Generated by Django 3.1.7 on 2021-05-06 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tiposdni',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipodni', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dni', models.IntegerField()),
                ('nombres', models.CharField(max_length=200)),
                ('tel', models.BigIntegerField()),
                ('correo', models.CharField(max_length=300)),
                ('url_selfi', models.ImageField(default='images/selfie/no-images.jpg', upload_to='images/selfie/')),
                ('url_documento', models.ImageField(default='images/doc/no-images.jpg', upload_to='images/doc/')),
                ('resultado_fac', models.CharField(max_length=20)),
                ('fecha', models.DateField(auto_now=True)),
                ('tipo_dni', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='principal.tiposdni')),
            ],
        ),
    ]
