# Generated by Django 2.2.5 on 2021-04-06 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_dni', models.IntegerField(max_length=10)),
                ('dni', models.IntegerField(max_length=10)),
                ('nombres', models.CharField(max_length=200)),
                ('tel', models.IntegerField(max_length=10)),
                ('correo', models.CharField(max_length=300)),
                ('url_selfi', models.CharField(max_length=5000)),
                ('url_documento', models.CharField(max_length=5000)),
                ('resultado_fac', models.CharField(max_length=20)),
                ('fecha', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Tiposdni',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipodni', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_dni', models.IntegerField(max_length=10)),
                ('dni', models.IntegerField(max_length=10)),
                ('nombres', models.CharField(max_length=200)),
                ('usuario', models.CharField(max_length=200)),
                ('contrasenia', models.CharField(max_length=200)),
                ('estado', models.IntegerField(max_length=10)),
            ],
        ),
    ]
