# Generated by Django 3.1.7 on 2021-04-29 01:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=100, unique=True, verbose_name='Username')),
                ('email', models.CharField(max_length=255, unique=True, verbose_name='Email')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Name')),
                ('lastname', models.CharField(blank=True, max_length=100, null=True, verbose_name='Lastname')),
                ('image', models.ImageField(blank=True, max_length=200, null=True, upload_to='perfil/', verbose_name='Image')),
                ('user_active', models.BooleanField(default=True)),
                ('user_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tiposdni',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipodni', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dni', models.IntegerField()),
                ('nombres', models.CharField(max_length=200)),
                ('usuario', models.CharField(max_length=200)),
                ('contrasenia', models.CharField(max_length=200)),
                ('estado', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='principal.estado')),
                ('tipo_dni', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='principal.tiposdni')),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dni', models.IntegerField()),
                ('nombres', models.CharField(max_length=200)),
                ('tel', models.BigIntegerField()),
                ('correo', models.CharField(max_length=300)),
                ('url_selfi', models.ImageField(default='images/selfie/no-images.jpg', upload_to='images/selfie/')),
                ('url_documento', models.ImageField(default='images/doc/no-images.jpg', upload_to='images/doc/')),
                ('resultado_fac', models.CharField(max_length=20)),
                ('fecha', models.DateField(auto_now=True)),
                ('tipo_dni', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='principal.tiposdni')),
            ],
        ),
    ]
