# Generated by Django 2.2.5 on 2021-04-06 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='dni',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='persona',
            name='tel',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='persona',
            name='tipo_dni',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='dni',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='estado',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='tipo_dni',
            field=models.IntegerField(),
        ),
    ]
