# Generated by Django 2.2.5 on 2021-04-07 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0002_auto_20210406_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='tipo_dni',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='principal.Tiposdni'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='estado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='principal.Estado'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='tipo_dni',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='principal.Tiposdni'),
        ),
    ]
