# Generated by Django 2.2.5 on 2021-04-07 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0003_auto_20210407_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='tel',
            field=models.BigIntegerField(),
        ),
    ]
