# Generated by Django 2.2.5 on 2021-04-07 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0004_auto_20210407_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='fecha',
            field=models.DateField(auto_now=True),
        ),
    ]
