# Generated by Django 2.2.5 on 2021-04-07 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0006_auto_20210407_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='url_selfi',
            field=models.ImageField(upload_to='Imagenes/'),
        ),
    ]
