# Generated by Django 2.2.5 on 2021-04-07 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0008_auto_20210407_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='url_selfi',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
