# Generated by Django 2.2.5 on 2021-04-07 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0009_auto_20210407_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='url_documento',
            field=models.ImageField(upload_to='images/doc/<django.db.models.fields.IntegerField>'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='url_selfi',
            field=models.ImageField(upload_to='images/selfie/<django.db.models.fields.IntegerField>'),
        ),
    ]
