# Generated by Django 2.2.5 on 2021-04-07 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0010_auto_20210407_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='url_documento',
            field=models.ImageField(upload_to='images/doc/<bound method Field.__str__ of <django.db.models.fields.IntegerField>>'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='url_selfi',
            field=models.ImageField(upload_to='images/selfie/<bound method Field.__str__ of <django.db.models.fields.IntegerField>>'),
        ),
    ]
