# Generated by Django 2.2.5 on 2021-04-07 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0012_auto_20210407_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='url_documento',
            field=models.ImageField(default='images/doc/no-img.jpg', upload_to='images/doc/'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='url_selfi',
            field=models.ImageField(default='images/selfie/no-img.jpg', upload_to='images/selfie/'),
        ),
    ]
